### ISSUE TITLE
Header Component for user route

### ISSUE THREAD

**Issue by tkbdsi** [thkruz/the-enhanced-scheduling-tool#20] opened 2022-02-18 17:42 UTC
Header component will likely not render "Member Availability" as there is no /user/ route

- [ ] If we think it appropriate, we could create a /user route which will essentially be a replica of the quick navigation on the lefthand side
- [ ] We should probably update the Header to display "Member Availability" on the route: /user/:id

**Comment by filmo003** [comment] 2022-02-23 19:44
Duplicate of AC in #8

**Closed** 2022-02-23 19:43 UTC
Labels: Bug
